Error while building container - No module named 'distutils.util'
I was getting the following error while using build_and_push - 

```bash

Removing intermediate container 4bfbe52ed3c7
 ---> 26df0bbf7bfa
Step 6/22 : RUN cd /tmp &&     curl -O https://bootstrap.pypa.io/get-pip.py &&     python get-pip.py 'pip<=18.1' && rm get-pip.py
 ---> Running in dc093d4f64f0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1734k  100 1734k    0     0  12.9M      0 --:--:-- --:--:-- --:--:-- 12.9M
Traceback (most recent call last):
  File "get-pip.py", line 22318, in <module>
    main()
  File "get-pip.py", line 198, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip._internal.main
  File "/tmp/tmpq9y5cy5d/pip.zip/pip/_internal/main.py", line 13, in <module>
  File "/tmp/tmpq9y5cy5d/pip.zip/pip/_internal/cli/autocompletion.py", line 11, in <module>
  File "/tmp/tmpq9y5cy5d/pip.zip/pip/_internal/cli/main_parser.py", line 7, in <module>
  File "/tmp/tmpq9y5cy5d/pip.zip/pip/_internal/cli/cmdoptions.py", line 19, in <module>
ModuleNotFoundError: No module named 'distutils.util'
The command '/bin/sh -c cd /tmp &&     curl -O https://bootstrap.pypa.io/get-pip.py &&     python get-pip.py 'pip<=18.1' && rm get-pip.py' returned a non-zero code: 1
+ docker tag fluent-sagemaker-fast-bert:1.0-gpu-py36 111652037296.dkr.ecr.us-west-2.amazonaws.com/fluent-sagemaker-fast-bert:1.0-gpu-py36
Error response from daemon: No such image: fluent-sagemaker-fast-bert:1.0-gpu-py36
+ docker push 111652037296.dkr.ecr.us-west-2.amazonaws.com/fluent-sagemaker-fast-bert:1.0-gpu-py36
The push refers to repository [111652037296.dkr.ecr.us-west-2.amazonaws.com/fluent-sagemaker-fast-bert]
An image does not exist locally with the tag: 111652037296.dkr.ecr.us-west-2.amazonaws.com/fluent-sagemaker-fast-bert
ec2-user@ip-172-16-13-100 [7]:~/SageMaker/DND/GitHub/fast-bert/container$ ls
bert  build_and_push.sh  Dockerfile_cpu  Dockerfile_gpu  Dockerfile_gpu_old  Dockerfile_pytorch_nvidia  pytorch_build_and_push.sh
ec2-user@ip-172-16-13-100 [7]:~/SageMaker/DND/GitHub/fast-bert/container$ diff Dockerfile_gpu ../../
amazon-sagemaker-examples/ fast-bert/                 gpt-2-Pytorch/             Reinvent2019Pytorch/       
ec2-user@ip-172-16-13-100 [7]:~/SageMaker/DND/GitHub/fast-bert/container$ diff Dockerfile_gpu ../../Reinvent2019Pytorch/
.git/               .gitignore          img/                .ipynb_checkpoints/ README-EE.md        README.md           src/                
ec2-user@ip-172-16-13-100 [7]:~/SageMaker/DND/GitHub/fast-bert/container$ diff Dockerfile_gpu ../../Reinvent2019Pytorch/src/
bonus/            boot.sh           impatient/        lab1/             lab2/             lab3/             lab4/             requirements.txt  scratch/          
ec2-user@ip-172-16-13-100 [7]:~/SageMaker/DND/GitHub/fast-bert/container$ diff Dockerfile_gpu ../../Reinvent2019Pytorch/src/lab2/
container/ img/       notebooks/ README.md  sm-data/   
ec2-user@ip-172-16-13-100 [7]:~/SageMaker/DND/GitHub/fast-bert/container$ diff Dockerfile_gpu ../../Reinvent2019Pytorch/src/lab2/container/
bert/               build_and_push.sh   Dockerfile_gpu      .ipynb_checkpoints/ 
ec2-user@ip-172-16-13-100 [7]:~/SageMaker/DND/GitHub/fast-bert/container$ diff Dockerfile_gpu ../../Reinvent2019Pytorch/src/lab2/container/Dockerfile_gpu 
14,21c14,21
<     build-essential \
<     curl \
<     jq \

```
Adding the package python3-distutils resolves this error, for me. 

```bash
    then apt-get install -y --no-install-recommends python3-distutils python3.7-dev \
```